import type { User as FirebaseUser } from 'firebase/auth'
import type { UserRole } from '@/modules/store/types'

/**
 * Extended user interface that includes Firebase user data and custom claims
 */
export interface AuthUser extends FirebaseUser {
  /**
   * User role (interviewer or candidate)
   * This is set via custom claims when signing in with magic link
   */
  role?: UserRole
}

/**
 * Authentication state interface
 */
export interface AuthState {
  /**
   * Current authenticated user, or null if not authenticated
   */
  user: AuthUser | null
  /**
   * Whether authentication state is being checked
   */
  loading: boolean
  /**
   * Any error that occurred during authentication
   */
  error: Error | null
}

/**
 * Magic link token claims
 * 
 * These claims are embedded in the JWT token generated by the Cloud Function
 */
export interface MagicLinkTokenClaims {
  /**
   * Room ID that the token grants access to
   */
  roomId: string
  /**
   * User role (interviewer or candidate)
   */
  role: UserRole
  /**
   * Token expiration timestamp (Unix epoch in seconds)
   */
  exp: number
  /**
   * Token issued at timestamp (Unix epoch in seconds)
   */
  iat: number
}

/**
 * Magic link token validation result
 */
export interface MagicLinkValidationResult {
  /**
   * Whether the token is valid
   */
  valid: boolean
  /**
   * Extracted token claims (if valid)
   */
  claims?: MagicLinkTokenClaims
  /**
   * Error message (if invalid)
   */
  error?: string
}

